/**
 * Init Wizard tests — non-interactive mode
 */

import { test } from 'node:test';
import assert from 'node:assert/strict';
import { runWizard, writeScript } from '../src/init-wizard.js';
import { readFileSync, unlinkSync, existsSync } from 'fs';

test('runWizard non-interactive returns valid script (template)', async () => {
  const script = await runWizard({ template: 'landing-page' });
  assert.ok(script);
  assert.equal(script.project.name, 'My Demo');
  assert.equal(script.scenes.length, 3);
  assert.equal(script.scenes[0].actions[0].type, 'goto');
  assert.equal(script.voice.engine, 'edge-tts');
});

test('runWizard non-interactive returns valid script (blank)', async () => {
  const script = await runWizard({ template: 'blank' });
  assert.ok(script);
  assert.equal(script.scenes.length, 1);
  assert.equal(script.scenes[0].name, 'intro');
});

test('runWizard non-interactive with invalid template falls back', async () => {
  const script = await runWizard({ template: 'nonexistent' });
  assert.ok(script);
  assert.ok(script.scenes.length > 0);
});

test('writeScript generates valid YAML', async () => {
  const script = await runWizard({ template: 'saas-demo' });
  const outPath = './_test_output.yaml';
  writeScript(script, outPath);
  assert.ok(existsSync(outPath));
  const content = readFileSync(outPath, 'utf-8');
  assert.ok(content.includes('project:'));
  assert.ok(content.includes('scenes:'));
  assert.ok(content.includes('name: "My Demo"'));
  assert.ok(content.includes('# Generated by: clawforge init'));
  assert.ok(content.includes('engine: "edge-tts"'));
  unlinkSync(outPath);
});

test('all templates produce valid output', async () => {
  const templates = ['landing-page', 'hackathon', 'saas-demo', 'tutorial', 'mobile-app'];
  for (const tid of templates) {
    const script = await runWizard({ template: tid });
    assert.ok(script, `Template ${tid} returned script`);
    assert.ok(script.scenes.length > 0, `Template ${tid} has scenes`);
    for (const scene of script.scenes) {
      assert.ok(scene.actions.length > 0, `Template ${tid}/${scene.name} has actions`);
      for (const action of scene.actions) {
        assert.equal(action.url === undefined || typeof action.url === 'string', true,
          `Template ${tid}/${scene.name}/${action.type}: url should be string or undefined`);
      }
    }
  }
});
